### ISSUE TITLE
中国式英雄登场了

### ISSUE THREAD

**Issue by WenjingBao** [re-ovo/awara#3]
谢谢dalao
![15747d3f-f2c7-4ba6-b712-f3a064223031_text](https://user-images.githubusercontent.com/25001011/227830219-601e1a81-2503-4df7-8a74-c4623500e931.gif)

**Comment by WenjingBao** [comment]
期待release

**Comment by re-ovo** [comment]
你这头像总让我感觉像编程培训班老师

**Comment by WenjingBao** [comment]
草，以前拍的艺术照，换了换了
